name: CI
on: push
jobs:
   Build:
     name: buikd
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - run: |
          npm init -y
          npm install express
          npm run build
       - uses: actions/upload-artifact@main
         with:
           name: web pack Artifacts
           path: /public
          
         
         
