name: CI
on: push
jobs:
   Build:
     name: buikd
     runs-on: ubuntu-latest
     steps:
       - run: |
          npm install
          npm run build
       - uses: actions/upload-artifacts@main
         with:
           name: web pack Artifacts
           path: /public
          
         
         
